sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FkTXh9shpXjUZt/IlWncRcwjl1g7tz/p1/PuIGdWNmS37YEdp8OUOceTc+xDE3bf9OpQehPoAFmm+XzO+zUp2hU4yKMb7NkSHF9st56hn2LOsxBYAgUg3+9TdKdeo5DHGWzGQTbZ1TcEVGA0JNQKza6vU5p2DsY23CHn4VngbV0xVWLFpjXQiJfr4ESREeBnDAlRlDnSrdGtXGNwxVZCKHuUTSaZfhWHm8vdZ3aOQfXLzX+gsjUdvWdESlF7Kh6Tq54qmBudvhZ7MGaI5OkC9Oj5jb2t00k8SvC+wHce9M+bvaO1UmJsPOYdAAV8aoPJhIJQna/shO7OE8631TZym6tiuLaELJWcvggdh1NjnmIVCdDDzJSEaox/goI8HHDVNEruPHP3KL2foZXkFUB/kmdg+xf053VDImAhNonaFnoCJyzEg3YiKvvYjyRbqir1NJ4ta6vjqexNKyoHOc7CRxkoHxjbZx2sWq9r/r7XNFQqFvXTYi45mBVz3zEYHLBDNT9toXgDwTd+aoCQtC4tj7hME9dWdGXqAIDP8m5ZSFOQmu4GNESEuAwvEzPAiCHKCRZsGccQjnhwnv0qXcnXuYfcOtlGIRk1bR5UKi8PBGfusGJbUo9ZJ6qNYs/EMdw0XVsmEESQ6qZzC59vLMhphHlbLC/1FH1byD5J+4dGTQY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Walden-and-On-The-Duty-Of-Civil-Disobedience_205
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy